services:
  postgres:
    image: postgres:15
    container_name: axiomatics-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres  # Password for 'postgres' superuser
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: